server:
  hostname: {{.HOSTNAME}}
  public_url: {{.PUBLIC_URL}}
  port: {{.PORT}}

tls:
  min_version: "1.3"
  cert_file: "config/certs/server.cert"
  key_file: "config/certs/server.key"

database:
  config:
    type: "sqlite"
    sqlite:
      path: "database/configdb.db"
      options: "_journal_mode=WAL&_busy_timeout=5000&_pragma=foreign_keys(1)"
      max_open_conns: 500
      max_idle_conns: 100
      conn_max_lifetime: 3600

  runtime:
    type: "sqlite"
    sqlite:
      path: "database/runtimedb.db"
      options: "_journal_mode=WAL&_busy_timeout=5000&_pragma=foreign_keys(1)"
      max_open_conns: 500
      max_idle_conns: 100
      conn_max_lifetime: 3600

  user:
    type: "sqlite"
    sqlite:
      path: "database/userdb.db"
      options: "_journal_mode=WAL&_busy_timeout=5000&_pragma=foreign_keys(1)"
      max_open_conns: 500
      max_idle_conns: 100
      conn_max_lifetime: 3600

crypto:
  encryption:
    key: "file://config/certs/crypto.key"
  password_hashing:
    algorithm: "PBKDF2"
  keys:
    - id: "default-key"
      cert_file: "config/certs/signing.cert"
      key_file: "config/certs/signing.key"

jwt:
  preferred_key_id: "default-key"

email:
  smtp:
    host: {{.SMTP_HOST}}
    port: {{.SMTP_PORT}}
    username: {{.SMTP_USERNAME}}
    password: {{.SMTP_PASSWORD}}
    from_address: {{.SMTP_FROM_ADDRESS}}
    enable_start_tls: {{.SMTP_ENABLE_START_TLS}}
    enable_authentication: {{.SMTP_ENABLE_AUTHENTICATION}}

cors:
  allowed_origins:
{{- range .CORS_ORIGINS }}
    - {{.}}
{{- end }}

passkey:
  allowed_origins:
    - {{.PUBLIC_URL}}

consent:
  enabled: false
